owncloud/market

.travis.yml
appinfo/info.xml
lib/AppStore/OCSClient.php
lib/Command/UpgradeApp.php
lib/MarketService.php
tests/unit/AppStore/OCSClientTest.php

Requires https://github.com/owncloud/core/pull/26588

Implementing market:install and market:upgrade

---

lib/Command/InstallApp.php
lib/Command/UpgradeApp.php
lib/MarketService.php

`occ market:install --local path/to/tarball.tar.gz`
or
`occ market:upgrade --local path/to/tarball.tar.gz`
Closes https://github.com/owncloud/market/issues/19

Install or update app from a local package

---

lib/Application.php
lib/Listener.php

Depends on https://github.com/owncloud/core/pull/27648

 Listen to upgradeAppStoreApps event

---

lib/MarketService.php

Allow to fill the cache

---

appinfo/info.xml

Reverts owncloud/market#24
github revert magic
@DeepDiver1975 to be merged before final

Enable by default

---

lib/MarketService.php

Requires https://github.com/owncloud/core/pull/27719
@VicDeo please review

Better exceptions

---

appinfo/app.php
lib/Application.php
lib/Listener.php
lib/MarketService.php

Listen to repair app event

---

.babelrc
package.json

This will fix the current compiling errors

Add .babelrc, Update uglify-js

---

lib/MarketService.php

Reproduction Steps:
1. Open Market app
2. Check owncloud.log
3. Observe
```
{"reqId":"ObXBdozom9QEozTFfNNI","level":3,"time":"2017-06-21T17:26:57+00:00","remoteAddr":"127.0.0.1","user":"D","app":"PHP","method":"GET","url":"/index.php/apps/market/apps","message":"version_compare() expects parameter 1 to be string, array given at /oc-tmp/apps/market/lib/MarketService.php#183"}
```

Fix sort of releases

---

package.json
src/components/Details.vue
src/styles/variables-theme.scss

Display *Show in marketplace* if an app is not *downloadable*

Check downloadable

---

appinfo/info.xml
lib/Application.php
lib/CheckUpdateBackgroundJob.php
lib/MarketService.php
lib/Notifier.php
tests/unit/CheckUpdateBackgroundJobTest.php

BackgroundJob to notify admins about app updates

---

lib/CheckUpdateBackgroundJob.php
tests/unit/CheckUpdateBackgroundJobTest.php

@DeepDiver1975 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/owncloud/market/

Scrutinizer Auto-Fixes

---

lib/CheckUpdateBackgroundJob.php
tests/unit/CheckUpdateBackgroundJobTest.php

Revert "Scrutinizer Auto-Fixes"

---

appinfo/info.xml
lib/Application.php
lib/CheckUpdateBackgroundJob.php
lib/MarketService.php
lib/Notifier.php
tests/unit/CheckUpdateBackgroundJobTest.php

Backport of https://github.com/owncloud/market/pull/108
Manually tested with OC10.

[Stable10] BackgroundJob to notify admins about app updates

---

lib/MarketService.php

Stable10 marketplace connection messages

---

lib/Command/InstallApp.php
lib/Command/ListApps.php
lib/Command/UnInstallApp.php
lib/Command/UpgradeApp.php

provide non-zero exit codes on failure

---

src/styles/theme.scss

Fixes: https://github.com/owncloud/market/issues/54
Don't forget to `npm run build` ;-)

Prevent overriding top right menu

---

src/components/Details.vue

Show the link to the publisher page if its set to public

Fix publisher link

---

CHANGELOG.md

This PR so far includes everything I could find in the history and we can use it to prepare the next release. 
If the information is okay, I will backport it to stable10 branch

[WIP] Update changelog for next release

---

src/components/Trial.vue
src/store.js

Fix "Start Start Enterprise trial" Button popping up while loading.

Fix flickering button

---

CHANGELOG.md
src/components/Details.vue

Fixes: https://github.com/owncloud/market/issues/144

Show date only if available. Show more detailed update information.

---

npm-shrinkwrap.json
package.json
src/components/BundleTile.vue
src/components/BundlesList.vue
src/components/Details.vue
src/components/List.vue
src/components/Tile.vue
src/components/Trial.vue
src/default.js
src/mixins.js
src/styles/theme.scss

Add markdown support for app description
Fixes: https://github.com/owncloud/market/issues/92

Add markdown support, export recurring methods to mixin-collection

---

src/components/BundleTile.vue
src/components/Trial.vue
src/store.js

Fixes: https://github.com/owncloud/market/issues/165

Make sure to install enterprise_key before installing bundle

---

CHANGELOG.md

Update changelog to remove outdated information

Removed already published changes from changelog

---

CHANGELOG.md
appinfo/info.xml

release 0.2.4

---

src/App.vue

Rebuild top-left navigation if app was (de)installed

---

composer.json

Define php minimum requirements - shall fix CI

---

CHANGELOG.md
appinfo/info.xml

For https://github.com/owncloud/market/issues/360

Add changelog for 0.2.5

---

package.json

Merge back release branch changes

Release 0.2.5

---

lib/Command/UpgradeApp.php
tests/unit/Command/UpgradeAppTest.php

Fixes #383 
TL;DR 
https://github.com/owncloud/market/blob/master/lib/MarketService.php#L326
0. Have any app to update from market
1. Try to do the update with `occ market:upgrade --all`
Before
```
deo@jah-mobile:1008> php occ market:upgrade --list
market : 0.2.5
deo@jah-mobile:1008> php occ market:upgrade --all
: Not installed ...
```
After
```
deo@jah-mobile:1008> php occ market:upgrade --all
market: Installing new version 0.2.5 ...
market: App updated.
```

Fix key when mapping the result

---

lib/Command/UpgradeApp.php

https://user-images.githubusercontent.com/10596560/48893262-3f2c8500-ee40-11e8-82bd-067d342b516d.png
https://user-images.githubusercontent.com/10596560/48893271-4784c000-ee40-11e8-85d2-894b7177e7df.png
```
> php occ market:upgrade password_policy
password_policy: update to 2.0.1 requires --major option.
```

Fix misleading message

---

README.md

CI fails because of existing unit test problems in ``master``

Switch build status badge from Travis to drone

---

src/components/Login.vue

Fix "Logged In" is shown despite being logged out

---

src/components/ApiForm.vue

The late PR: https://github.com/owncloud/market/pull/155

Hide 'Edit/Add API Key' button if not changeable

---

lib/MarketService.php
src/components/Details.vue
tests/unit/MarketServiceTest.php

Fixes #113 
We probably should not show the Uninstall button in the frontend

prevent uninstalling market app from within market app

---

.drone.yml
appinfo/info.xml
composer.json
composer.lock

core stable10 no longer supports PHP 5.6
https://github.com/owncloud/core/pull/34698

Drop PHP 5.6

---

CHANGELOG.md
Makefile
appinfo/info.xml

Closes https://github.com/owncloud/market/issues/447

Release 0.4.0

---

composer.lock
phpunit.xml
tests/unit/CheckUpdateBackgroundJobTest.php
tests/unit/Command/InstallAppTest.php
tests/unit/Command/ListAppsTest.php
tests/unit/Command/UnInstallAppTest.php
tests/unit/Command/UpgradeAppTest.php
tests/unit/HttpServiceTest.php
tests/unit/MarketControllerTest.php
tests/unit/MarketServiceTest.php
tests/unit/VersionHelperTest.php

1) Adjust PHPUnit Framework namespace for PHPUnit6
2) phpunit enable failOnRisky
3) Updating symfony/polyfill-mbstring (v1.10.0 => v1.11.0)

Phpunit 5 6

---

CHANGELOG.md
appinfo/info.xml

Release 0.5.0

---

.drone.starlark
.drone.yml

1) Reverse the drone `db_timeout: 120` that was added yesterday in PR #506 - 120 is now the default in `owncloudci/core`
2) Apply the current latest drone starlark code, like in activity app PR https://github.com/owncloud/activity/pull/804
CI

Update drone starlark 20191121

---

.drone.starlark
phpunit.xml
tests/unit/CheckUpdateBackgroundJobTest.php
tests/unit/Command/InstallAppTest.php
tests/unit/Command/ListAppsTest.php
tests/unit/Command/UnInstallAppTest.php
tests/unit/Command/UpgradeAppTest.php
tests/unit/HttpServiceTest.php
tests/unit/MarketControllerTest.php
tests/unit/MarketServiceTest.php
tests/unit/NotifierTest.php
tests/unit/PageControllerTest.php
tests/unit/VersionHelperTest.php

Similar to https://github.com/owncloud/configreport/pull/121

Adjust tests

---

.drone.starlark
tests/unit/Command/InstallAppTest.php
tests/unit/Command/UnInstallAppTest.php
tests/unit/Command/UpgradeAppTest.php
tests/unit/HttpServiceTest.php
tests/unit/MarketServiceTest.php
tests/unit/NotifierTest.php
vendor-bin/owncloud-codestyle/composer.json

like done in core https://github.com/owncloud/core/pull/36580
and apply latest drone starlark code changes
Note: there was no effect here on `.drone.yml`

Coding standard 2.0.0

---

.drone.star
lib/CheckUpdateBackgroundJob.php
lib/Command/InstallApp.php
lib/Command/ListApps.php
lib/Command/UnInstallApp.php
lib/Command/UpgradeApp.php
lib/Controller/MarketController.php
lib/HttpService.php
lib/MarketService.php
lib/Notifier.php
lib/VersionHelper.php
phpstan.neon
vendor-bin/phpstan/composer.json

Related - owncloud/QA#642
Update phpstan to 0.12

[Tests-Only] Update phpstan to latest version

---

.gitignore
tests/unit/Command/InstallAppTest.php
tests/unit/Command/ListAppsTest.php
tests/unit/Command/UnInstallAppTest.php
tests/unit/Command/UpgradeAppTest.php

Part of https://github.com/owncloud/QA/issues/647

[Tests-Only] Implement PHPUnit v8

---

CHANGELOG.md
appinfo/info.xml
lib/MarketService.php
src/components/BundleTile.vue
tests/unit/MarketServiceTest.php

Closes https://github.com/owncloud/market/issues/574

Merge back Release 0.6.0

---

appinfo/info.xml
src/App.vue
src/components/Trial.vue

Prompts the user to upgrade his owncloud installation as soon as he hits the "Start enterprise trial" button.
This branch was created from 0.5.0 tag.
#582

Notification about new trial

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

- merge after #651 
Closes #651

Merge back Release 0.6.1

---

.drone.star

Fixes #755 
Part of https://github.com/owncloud/QA/issues/687

[tests-only] Update latest .drone.star code from activity app

---

tests/unit/HttpServiceTest.php

Fixes https://github.com/owncloud/market/issues/801

[tests-only] Adjust php unit tests to ensure compatibility with PHPUnit v9.5

---

.drone.star
vendor-bin/phan/composer.json

1) Update to latest .drone.star code
2) Bump PHP phan to major version 5
Part of https://github.com/owncloud/QA/issues/696

[tests-only] Update to latest .drone.star code and bump PHP phan to major version 5

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

merge after successful release #871

merge back Release 0.6.2

---

lib/HttpService.php

https://github.com/owncloud/core/pull/39368 bumps Guzzle to v7 in core. These changes are necessary to make it work with this app.

Add compatibility with Guzzle 7

---

package-lock.json
package.json

This reverts commit df2bd7f8035d1f9ddf3b4a35aba07cfe551f56ae.

Revert "Bump uikit from 3.0.0-rc.26 to 3.15.1"

---

.drone.star
.gitignore

it is better to use directory references from the dir var, rather than using the hard-coded values in every use case.
- https://github.com/owncloud/QA/issues/734#issue-1173320353
- CI

[full-ci]Use directory references from global dir variable in drone.star file

---

tests/acceptance/features/cliMain/marketInstallUpgradeUninstall.feature

Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines
- Part of https://github.com/owncloud/QA/issues/769
- :robot:

[full-ci] [tests-only] Refactored inter scenarios space

---

.drone.star
appinfo/app.php
composer.json
composer.lock
lib/Application.php
lib/CheckUpdateBackgroundJob.php
lib/Command/InstallApp.php
lib/Command/UnInstallApp.php
lib/Command/UpgradeApp.php
lib/Controller/LocalAppsController.php
lib/Controller/MarketController.php
lib/Controller/PageController.php
lib/Notifier.php
phpstan.neon
tests/unit/CheckUpdateBackgroundJobTest.php
tests/unit/Command/InstallAppTest.php
tests/unit/Command/ListAppsTest.php
tests/unit/Command/UnInstallAppTest.php
tests/unit/Command/UpgradeAppTest.php
tests/unit/MarketControllerTest.php
tests/unit/MarketServiceTest.php
vendor-bin/behat/composer.json
vendor-bin/owncloud-codestyle/composer.json
vendor-bin/phpstan/composer.json

- update `.drone.star` code from activity app
- update tool dependencies
- update to coding-style 4.1

[tests-only] [full-ci] Update tool dependencies and drone CI code

---

.drone.star

- remove the use of `drone_token`
- adjust the use of the `cache_s3` tokens to use the names now available
Part of issue https://github.com/owncloud/QA/issues/818

[CI][full-ci]Drone star edited

---

appinfo/routes.php
lib/Controller/MarketController.php
lib/HttpService.php
lib/MarketService.php
tests/unit/HttpServiceTest.php
tests/unit/MarketControllerTest.php
tests/unit/MarketServiceTest.php

removing left overs from https://github.com/owncloud/market/pull/443 which are no longer used on frontend side

chore: remove unused code

---

.drone.star

Sending notification to talk.owncloud
Part of owncloud/QA#846

[test-only]  send notifications to talk.owncloud

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

Merge back Release 0.9.0
