- lib/Controller/MarketController.php
0. Install OC 10. Environment: PHP 7.0
1. Install app from market
2. Browse to the market page again, when app is installed.
3. tail `data/owncloud.log`
```
> tail data/owncloud.log      
{"reqId":"JP5lXdGK9RWCvRUCoVpU","level":3,"time":"2017-04-19T19:56:17+00:00","remoteAddr":"127.0.0.1","user":"D","app":"PHP","method":"GET","url":"/index.php/apps/market/apps","message":"Only variables should be passed by reference at /apps/market/lib/Controller/MarketController.php#107"}
```
> Get rid of Only variables should be passed by reference for PHP 7

- lib/Controller/MarketController.php
- lib/MarketService.php
- src/App.vue
- src/components/Details.vue
- src/components/List.vue
- src/components/Navigation.vue
- src/components/UpdateList.vue
- src/store.js
Also includes:
* improved error handling
* consolidated application actions
> Introduce uninstalling

- lib/Listener.php
- lib/MarketService.php
Because the app was already installed, no migrations must be run at this
stage. Later on, the upgrade process might notice a version change and
run migrations anyway. This part ensures it doesn't happen twice during
the upgrade process.
Tested as follows:
1. Install 9.1.5 enterprise
1. Enable user_ldap
1. Replace the source code with OC 10.0.1RC1 enterprise from tarball
1. Patch with https://github.com/owncloud/core/pull/27930
1. Patch with https://github.com/owncloud/core/pull/27934
1. Patch with this PR here
1. Edit config.php to point to the correct cert and staging marketplace (if applicable, need the user_ldap app to be there)
1. Run `occ upgrade`
Before the fixes: LDAP migrations run twice and getting TableAlreadyExistsException because it tries to create the same tables twice. …
> Skip migrations when reinstalling missing code

- appinfo/routes.php
- lib/Controller/MarketController.php
- lib/Exception/LicenseKeyAlreadyAvailableException.php
- lib/Exception/MarketException.php
- lib/MarketService.php
- src/App.vue
- src/components/ApiForm.vue
- src/components/BundleTile.vue
- src/components/Details.vue
- src/components/Navigation.vue
- src/components/Trial.vue
- src/store.js
- webpack.config.js
This PR contains the UI and backend for the trial process feature. It requests the demo license key from the marketplace, saves the key in appconfig and installs all enterprise applications.
Additionally the enterprise_key app will be able to load enterprise keys from the appconfig if there is no key configured in config.php.
> Enterprise demo (trial) process

- lib/Command/ListApps.php
I was just using the command line occ market commands. The output of market:list comes out in whatever order the JSON happens to have been delivered in.
This output is intended for human consumption (as well as the possibility that someone will write a script that eats it), so it is friendly to sort it alphabetically.
One day it could be enhanced to group the list by category, and that will require a different sorting.
I thought about putting the sorting inside listApps(). But actually each caller of listApps() might want sorting by all sorts of different fields, not necessarily by id.
> Sort occ market:list in alphabetical order

- .travis.yml
- appinfo/info.xml
- lib/Command/InstallApp.php
- lib/Command/UnInstallApp.php
- lib/Command/UpgradeApp.php
- lib/MarketService.php
- tests/unit/MarketServiceTest.php
- fixes #111 
- fixes #117 
Blocker - needs 10.0.3 release upfront - see https://github.com/owncloud/core/pull/28543
> Handle cluster setup

- src/components/Trial.vue
Hide 'Start Enterprise trial' button instead of disabling it if license-key exists.
Fixes: https://github.com/owncloud/market/issues/135
> Hide 'Start Enterprise trial' button

- lib/Command/InstallApp.php
- lib/Command/ListApps.php
- lib/Command/UnInstallApp.php
- lib/Command/UpgradeApp.php
OCC market commands would always return 0 as exit code, even if a failure occured. This PR is related to #133 to provide non-zero exit codes (exit-code 1 on failure). When a failure occured
Tested manually:
```
$ php occ market:upgrade theme-enterprise
theme-enterprise: Installing new version 2.0.0 ...
theme-enterprise: No marketplace connection
$ echo $?
1
```
> provide non-zero exit codes on failure

- lib/MarketService.php
This PR adresses #133  - market app only shows `No marketplace connection` even though we are having different (actionable) error cases:
1) No api key provided, and trying to download an application that is not free to download
2) Invalid API Key provided
3) Valid Api Key, but product is not purchased on marketplace (no valid subscription)
1) **No api key provided**
```
php occ market:upgrade theme-enterprise
theme-enterprise: Installing new version 2.0.0 ...
theme-enterprise: Marketplace API key missing
```
Frontend shows
2) ** Invalid APIKEY**
```
$ php occ market:upgrade theme-enterprise
theme-enterprise: Invalid marketplace API key provided
```
3) ** Purchase required**
```
php occ market:upgrade theme-enterprise
theme-enterprise: Installing new version 2.0.0 ...
theme-enterprise: …
```
> Error messages for marketplace errors

- src/components/Trial.vue
… instead of disabling it if license-key exists
Original PR: https://github.com/owncloud/market/pull/142
> [stable10] Hide 'Start Enterprise trial' button

- CHANGELOG.md
- appinfo/info.xml
Changelog is the same as #164 since master and stable10 only differ in one open pr that is cosmetic nature (box shadow).
> [stable10] update changelog/version for release of 0.2.2

- .babelrc
- npm-shrinkwrap.json
- package.json
One of our dependencies depends on an explicit old version of `js-beautify` which was deleted, this makes the build fail. Explicitly depending on a current version fixes this issue.
https://github.com/beautify-web/js-beautify/issues/1247
> added explicit js-beautify dependency

- CHANGELOG.md
- src/components/Details.vue
- src/store.js
This rebuilds the top left navigation and adds or removes apps whether they were just installed or deleted.
Since `OC.Settings.Apps` is only available in the settings section, I copied and slimed the `rebuildNavigation()` method in the market.
Fixes: https://github.com/owncloud/market/issues/170
>  Rebuild navigation after application (un)install

- .travis.yml
- appinfo/routes.php
- lib/Controller/MarketController.php
- npm-shrinkwrap.json
- package.json
- src/App.vue
- src/components/Trial.vue
- src/store.js
Fixes: https://github.com/owncloud/market/issues/179
> Add initial notice

- lib/MarketService.php
Fixes #260 
When caching is active, the first request would be cached and if the apikey / enterprise trail is started afterward, it would lead to not being able to install enterprise trail apps
Note:
There is still an open scenario, that when the user changes config.php manually to update licensekey and apikey that the cache would persist.
We should document that changing/adding theses values requires a cache invalidation
> Invalidate cache on change of apikey / enterprise trail

- lib/Notifier.php
- tests/unit/NotifierTest.php
Fixes https://github.com/owncloud/market/issues/270
Note: I see a code path that can trigger this behavior but was failed to reproduce it on my instance according to the steps from the issue:
- You install an app
- You enable and app
- It utilises appconfig keys
- You disable the app
- An app update is published
- Marketplace notifcation created for the admin
- You uninstall the app (folder actually removed)
- You dismiss the update notification
Now - everytime the marketplace update cron runs you get a notification for an update to an app that you have disabled AND uninstalled. Every time. Even if you dismiss.
> Prevent update notifications from uninstalled apps

- package.json
This is because we observed that neither node v4 nor node v10 can build fine.
I used node v8 locally and building works.
> Set max node version

- lib/Application.php
- lib/CheckUpdateBackgroundJob.php
- lib/Command/InstallApp.php
- lib/Command/UpgradeApp.php
- lib/Controller/MarketController.php
- lib/HttpService.php
- lib/Listener.php
- lib/MarketService.php
- lib/VersionHelper.php
- src/components/Details.vue
- src/components/UpdateList.vue
- src/store.js
- tests/unit/CheckUpdateBackgroundJobTest.php
- tests/unit/Command/InstallAppTest.php
- tests/unit/Command/UpgradeAppTest.php
- tests/unit/HttpServiceTest.php
- tests/unit/MarketServiceTest.php
- tests/unit/VersionHelperTest.php
- major (10 to 11 and like this) still DOES  upgrade apps  from 1.0 to 2.0 (if available)
- minor (10 to 10.1 and like this) does NOT apps upgrade from 1.0 to 2.0
- `market:upgrade` still DOES upgrade 1.0 to 1.1
- `market:upgrade` does NOT upgrade 1.0 to 2.0
- `market:upgrade --major` DOES upgrade 1.0 to 2.0
- `market:install` does NOT upgrade 1.0 to 2.0 if the app is already installed
- `market:install` still DOES upgrade 1.0 to 1.1 if the app is already installed
- Shows both 1.1 and 2.0 for 1.0, 1.1 is default
- Generates notifications both for 1.1 and 2.0 
(Depends on https://github.com/owncloud/core/pull/32491)
0.3.5 to 0.3.5
```
deo@jah-mobile:> php occ market:upgrade --local ../customgroups.tar.gz 
customgroups: ../customgroups.tar.gz has the same or older version of the app
``` …
> Refactor the app to allow choosing between next minor and major update

- tests/unit/Command/UpgradeAppTest.php
These methods return null without mocking so the  strict comparison against `false` fails.
> Fix failing upgrade app tests

- appinfo/routes.php
- lib/Controller/MarketController.php
- lib/Controller/PageController.php
- lib/HttpService.php
- lib/MarketService.php
- src/App.vue
- src/components/ApiForm.vue
- src/components/Login.vue
- src/store.js
- tests/unit/HttpServiceTest.php
- tests/unit/MarketServiceTest.php
- tests/unit/PageControllerTest.php
Login directly from market-app to auto-install your api-key. 
- Market app send its callback-url and [PKCE](https://tools.ietf.org/html/rfc7636)-Challenge to marketplace.
- A marketplace login and approval prompt is presented to the user.
- If user approves prompt, a one-time token is generated and forwarded to the market app.
- The Token is used together with PKCE-Verify-code by market app to retrieve the api-key.
This PR can be tested against staging marketplace by setting appstoreurl.
This is *NOT* OAuth because OAuth requires a static callback-url
Closes #425
> Marketplace login

- lib/Controller/LocalAppsController.php
- lib/Controller/MarketController.php
- tests/unit/MarketControllerTest.php
If the api-key is configured via config.php the api-key is still leaked via XHR-Responses. This PR hides the API-Key in this case. Contrary to assumptions made in #453  the frontend does not need any changes as it seems to be able to handle the missing apiKey-field without errors.
Fixes #453
> Hide api key in xhr-responses if key is configured in config.php

- src/components/Trial.vue
resolves #463 
PR adds a text to start-enterprise-trial modal that explains where a user can get an API key. 
@dercorn I made several grep searches in the repo and I found the message "API key missing" only here. I hope it is the place that you suggested to add an explanation.
> add a note to explain where to get api key

- composer.lock
```
composer update
Package operations: 0 installs, 4 updates, 0 removals
- Updating jms/serializer (1.13.0 => 1.14.0): Downloading (100%)         
- Updating symfony/debug (v3.4.23 => v3.4.28): Loading from cache
- Updating symfony/console (v3.4.23 => v3.4.28): Loading from cache
- Updating symfony/process (v3.4.23 => v3.4.28): Loading from cache
Writing lock file
Generating autoload files
```
> Bump symfony (v3.4.23 => v3.4.28) and jms/serializer (1.13.0 => 1.14.0)

- composer.lock
```
composer update
Package operations: 0 installs, 5 updates, 0 removals
- Updating guzzlehttp/guzzle (6.3.3 => 6.4.1): Downloading (100%)         
- Updating psr/log (1.1.0 => 1.1.1): Loading from cache
- Updating symfony/debug (v3.4.30 => v3.4.33): Loading from cache
- Updating symfony/console (v3.4.30 => v3.4.33): Loading from cache
- Updating symfony/process (v3.4.30 => v3.4.33): Loading from cache
Writing lock file
Generating autoload files
```
https://symfony.com/blog/symfony-3-4-33-released
> Bump dependencies 20191101

- .drone.starlark
- .drone.yml
- Makefile
If I clone this repo and immediately `make test-php-unit` it dies. I first need to know to do `composer install` or some other `make` target that will install the composer dependencies.
Add the composer dependencies so that `make test-php-unit` will "just work"
(I noticed this when sorting out `Makefile` for the metrics app)
Local `make test-php-unit`
> Add php unit composer dependencies to Makefile

- composer.lock
and guzzle 6.5.3
```
Generating autoload files
Package operations: 2 installs, 4 updates, 0 removals
- Installing symfony/polyfill-php72 (v1.15.0): Loading from cache
- Installing symfony/polyfill-intl-idn (v1.15.0): Loading from cache
- Updating guzzlehttp/guzzle (6.5.2 => 6.5.3): Loading from cache
- Updating symfony/debug (v3.4.39 => v3.4.40): Loading from cache
- Updating symfony/console (v3.4.39 => v3.4.40): Loading from cache
- Updating symfony/process (v3.4.39 => v3.4.40): Loading from cache
```
> Update symfony 3.4.40

- Makefile
So developers can `make clean` properly.
> Clean vendor-bin from Makefile

- composer.lock
```
composer update
Package operations: 0 installs, 7 updates, 0 removals
- Updating symfony/polyfill-php72 (v1.15.0 => v1.17.0): Loading from cache
- Updating symfony/polyfill-mbstring (v1.15.0 => v1.17.0): Loading from cache
- Updating symfony/polyfill-intl-idn (v1.15.0 => v1.17.0): Loading from cache
- Updating guzzlehttp/guzzle (6.5.3 => 6.5.4): Loading from cache
- Updating symfony/debug (v3.4.40 => v3.4.41): Loading from cache
- Updating symfony/console (v3.4.40 => v3.4.41): Loading from cache
- Updating symfony/process (v3.4.40 => v3.4.41): Downloading (100%)         
```
> Bump PHP dependencies as at 20200605

- composer.lock
and phpoption/phpoption (1.7.3 => 1.7.4)
```
composer update
Package operations: 0 installs, 4 updates, 0 removals
- Updating phpoption/phpoption (1.7.3 => 1.7.4): Downloading (100%)         
- Updating symfony/debug (v3.4.41 => v3.4.42): Loading from cache
- Updating symfony/console (v3.4.41 => v3.4.42): Loading from cache
- Updating symfony/process (v3.4.41 => v3.4.42): Loading from cache
```
> Bump symfony (v3.4.41 => v3.4.42)

- .drone.star
- composer.json
- composer.lock
Issue https://github.com/owncloud/core/issues/38067
See issue for details - `behat` acceptance tests need to use PHP  7.4 for the dependencies to sort themselves out with composer 2.0
`composer.json` is bumped to PHP 7.2 because `appinfo/info.xml` already has core min version 10.5 - which requires min PHP 7.2 anyway.
> Adjust PHP dependencies for composer 2.0

- lib/Controller/MarketController.php
- lib/MarketService.php
https://drone.owncloud.com/owncloud/market/1830/4/4
```
php -d zend.enable_gc=0 vendor-bin/phpstan/vendor/bin/phpstan analyse --memory-limit=4G --configuration=./phpstan.neon --no-progress --level=5 appinfo lib
------ ---------------------------------------------------------------------- 
Line   lib/Controller/MarketController.php                                   
------ ---------------------------------------------------------------------- 
286    Parameter #2 $cmp_function of function usort expects callable(mixed,  
mixed): int, Closure(mixed, mixed): bool given.                       
------ ---------------------------------------------------------------------- 
------ ---------------------------------------------------------------------- 
Line   lib/MarketService.php …
```
> Fix version_compare calls

- lib/CheckUpdateBackgroundJob.php
- tests/unit/CheckUpdateBackgroundJobTest.php
Related to https://github.com/owncloud/enterprise/issues/4250 as notifications URLs shouldn't be absolute to prevent problems with CORS.
> Use relative url instead of absoulute url

- composer.lock
```
$ composer update
Updating dependencies
Lock file operations: 1 install, 8 updates, 0 removals
- Upgrading doctrine/annotations (1.12.1 => 1.13.1)
- Locking psr/cache (1.0.1)
- Upgrading symfony/console (v4.4.22 => v4.4.24)
- Upgrading symfony/polyfill-intl-idn (v1.22.1 => v1.23.0)
- Upgrading symfony/polyfill-intl-normalizer (v1.22.1 => v1.23.0)
- Upgrading symfony/polyfill-mbstring (v1.22.1 => v1.23.0)
- Upgrading symfony/polyfill-php72 (v1.22.1 => v1.23.0)
- Upgrading symfony/polyfill-php73 (v1.22.1 => v1.23.0)
- Upgrading symfony/polyfill-php80 (v1.22.1 => v1.23.0)
Writing lock file
```
> Bump symfony and other PHP dependencies

- lib/HttpService.php
Due to https://github.com/owncloud/core/pull/39554, `null` will be transformed to an empty string when retrieving values from the `oc_appconfig` table. This makes the market app unusable in this scenario, so we need to omit the API key if empty.
Related to https://github.com/owncloud/core/issues/39616
> Fix issues when the market API key is an empty string

- composer.lock
```
$ composer update
Updating dependencies
Lock file operations: 0 installs, 4 updates, 0 removals
- Upgrading phpstan/phpdoc-parser (1.4.2 => 1.4.5)
- Upgrading symfony/console (v5.4.7 => v5.4.8)
- Upgrading symfony/process (v5.4.7 => v5.4.8)
- Upgrading symfony/string (v5.4.3 => v5.4.8)
Writing lock file
```
> Bump Symfony 5.4.8

- phpunit.xml
This PR moves unit tests into tests/unit folder. And also tidy up the `phpunit.xml` to make standard format for all oc-apps as much as possible.
- Part of https://github.com/owncloud/impersonate/issues/198
> [tests-only][full-ci]Tidy up the phpunit xml file for Market app

- .drone.star
- Makefile
- lib/Command/InstallApp.php
- lib/Command/UpgradeApp.php
- tests/acceptance/config/behat.yml
- tests/acceptance/features/bootstrap/MarketContext.php
- tests/acceptance/features/bootstrap/bootstrap.php
- tests/acceptance/features/cliMain/marketInstallUpgradeUninstall.feature
- tests/acceptance/features/cliMain/marketList.feature
- vendor-bin/behat/composer.json
The PHP unit tests were passing both before and after PR #817 - so the unit tests were not effective in finding the problem with code after the Guzzle7 update in core. See issue #1029 
To cover the real Guzzle client code that lists available apps and downloads app tarballs from the market-place, we really have to do real requests to the market-place. I looked at the unit tests and it didn't look like it would be easy/possible to mock out stuff while still actually covering the things that might go wrong.
So I have added acceptance tests. The downside is that they require the live production market-place server to be up. So they might sometimes fail if the market-place server is down (for maintenance or broken or...) The tests only run in the CI of this app, so it is not going to be an …
> [tests-only] [full-ci] Add acceptance tests

- lib/Command/InstallApp.php
- tests/unit/Command/InstallAppTest.php
> Update suggested use for major update

- lib/Command/InstallApp.php
- lib/Command/ListApps.php
- lib/Command/UnInstallApp.php
- lib/Command/UpgradeApp.php
- vendor-bin/phan/composer.json
Symfony 5 will require this, so be prepared.
For Symfony 4 it is optional.
Preparation for https://github.com/owncloud/core/issues/39630
> Always return an int from Symfony Command execute method

- package-lock.json
- package.json
TRY to bump security related vendor js dependencies, some dependencies still do not have fixed the peer dependency.
https://github.com/owncloud/market/security/dependabot?page=2&q=is%3Aopen
We're not able to test the build steps (or all contained scripts at all) on our dev machine, the repo still depends on node 8.
Recommendation: update everything to a more modern environment, this is not doable quick, this needs time, cc.: @jnweiger
> chore: bump security related js vendor dependencies

- Makefile
@DeepDiver1975 your
rm js/market.bundle.js
fails in the nightly builds:
```
rm js/market.bundle.js
rm: cannot remove 'js/market.bundle.js': No such file or directory make: *** [Makefile:53: clean] Error 1
```
I am introducing a -f here to make it pass, but please double check, if this hides a logic error somewhere else...
> Update Makefile to fix make dist
